[package]
name = "lychee"
description = "A modern computer vision library."
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]
license = "MIT/Apache-2.0"

[dependencies.lychee-core]
path = "../μcrates/core"
version = "0.1.*"

[dependencies.lychee-euclidean]
path = "../μcrates/euclidean"
version = "0.1.*"

[dependencies.lychee-ext]
path = "../μcrates/ext"
version = "0.1.*"

[dependencies.lychee-image]
path = "../μcrates/image"
version = "0.1.*"

[dependencies.lychee-linear]
path = "μcrates/linear"
version = "0.1.*"

[dependencies.lychee-motion]
path = "../μcrates/motion"
version = "0.1.*"

[dependencies.lychee-tracking]
path = "../μcrates/tracking"
version = "0.1.*"