[package]
name = "caribou-ext"
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]
license = "MIT/Apache-2.0"

[dependencies.caribou-euclidean]
path = "../euclidean"
version = "0.1.0"