[package]
name = "lychee-tracking"
version = "0.1.0"
authors = ["Jony <jonysy@users.noreply.github.com>"]

[dependencies]
extensions = { git = "https://github.com/jonysy/extensions.git" }

[dependencies.lychee-core]
path = "../core"
version = "0.1.0"

[dependencies.lychee-euclidean]
path = "../euclidean"
version = "0.1.0"

[dependencies.lychee-extn]
path = "../extn"
version = "0.1.0"

[dependencies.lychee-image]
path = "../image"
version = "0.1.0"